# Generated by Django 5.0.3 on 2024-03-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tourcomment_tour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourComment',
        ),
    ]
