# Generated by Django 5.0.3 on 2024-03-25 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tourreview_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourreview',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
