# Generated by Django 5.0.3 on 2024-03-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tourcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourcomment',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='tourcomment',
            old_name='data',
            new_name='date',
        ),
    ]
