# Generated by Django 5.0.3 on 2024-03-23 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tourcomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tours.tourcomment'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_bus_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tours.bustourtype'),
        ),
    ]
