# Generated by Django 5.0.3 on 2024-04-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_tourtags_tour_description_tour_tour_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourImgList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_img', models.CharField(max_length=100)),
                ('img_url', models.ImageField(upload_to='uploads/tours')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='img_list',
            field=models.ManyToManyField(to='tours.tourimglist'),
        ),
    ]
