# Generated by Django 5.0.3 on 2024-03-23 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_tour_comments_alter_tour_tour_bus_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=600)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='tour',
            name='comments',
        ),
        migrations.DeleteModel(
            name='TourComment',
        ),
        migrations.AddField(
            model_name='tour',
            name='comments',
            field=models.ManyToManyField(to='tours.tourcomments'),
        ),
    ]
