# Generated by Django 5.0.3 on 2024-03-23 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tourcomments_remove_tour_comments_delete_tourcomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='comments',
        ),
        migrations.AddField(
            model_name='tour',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tours.tourcomments'),
        ),
    ]
