# Generated by Django 5.0.3 on 2024-03-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_remove_tour_comments_tour_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='comments',
        ),
        migrations.AddField(
            model_name='tour',
            name='comments',
            field=models.ManyToManyField(to='tours.tourcomments'),
        ),
    ]
