# Generated by Django 5.0.3 on 2024-03-23 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_remove_tour_comments_tour_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='comments',
        ),
        migrations.AddField(
            model_name='tour',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='tours.tourcomments'),
        ),
    ]
