# Generated by Django 5.0.3 on 2024-04-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_tourcity_tour_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcity',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
