# Generated by Django 5.0.3 on 2024-03-23 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_remove_tour_comments_tour_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourcomments',
            old_name='comment',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='tour',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tourcomments'),
        ),
    ]
