# Generated by Django 5.0.3 on 2024-04-23 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_alter_tour_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tours.tourcity'),
        ),
    ]
