# Generated by Django 5.0.3 on 2024-03-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_remove_tour_comments_tour_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to='tours.tourcomments'),
        ),
    ]
