# Generated by Django 5.0.3 on 2024-04-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_alter_tour_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
