# Generated by Django 5.0.3 on 2024-03-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_alter_tour_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='comments',
            field=models.ManyToManyField(to='tours.tourcomments'),
        ),
    ]
