# Generated by Django 5.0.3 on 2024-04-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_alter_tourcity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='city',
        ),
    ]
