# Generated by Django 5.0.3 on 2024-03-24 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_remove_tour_comments_tourcomments_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcomments',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tour'),
        ),
    ]
