# Generated by Django 5.0.3 on 2024-03-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_alter_tourcomments_tour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourComments',
        ),
    ]
