# Generated by Django 5.0.3 on 2024-04-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_tour_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcity',
            name='favorite_city',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
