# Generated by Django 5.0.3 on 2024-04-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_tourcity_favorite_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='full_description',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
