# Generated by Django 5.0.3 on 2024-04-26 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_tour_full_description_alter_tour_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='full_description',
        ),
    ]
