# Generated by Django 5.0.3 on 2024-03-24 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_tourreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourreview',
            name='tours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.tour'),
        ),
    ]
